config/routes.rb
Rails.application.routes.draw do
  get 'page/checkout' 
  get 'page/confirmation'
  get 'page/order'

  resources :carts
  resources :line_items
  resources :products
  resources :charges
  devise_for :users

  root 'home#index'
  
 get 'account' => 'account#index'
 get "/account/:page" => "account#show"

end

app/views/page/checkout.html.erb
<h1>Checkout Page</h1>
    <br><br>
    <form action="/page/confirmation" method="GET">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_6pRNASCoBOKtIshFeQd4XMUh"
    data-amount=@total
    data-name="Health Spa Dublin"
    data-description="Checkout"
    data-image="assest/images/spa1.jpg"
    data-locale="auto">
  </script>
</form>
   <!-- <div id = "div_container">
    <div id = "form_div">
    <p>Cardholders Name: </p>
    <br>
    <p>Card Number: </p>
    <br>
    <p>Expiry Date: </p>
    </div>
    
    <div id = "input_div">
        <br>
        <input type = "text" name = "name" id = "name">
        <br><br><br><br>
        <input type = "text" name = "card_number" id = "card_number">
        <br><br><br><br><br>
        <input type = "text" name = "month" id = "month"><input type = "text" name = "year" id = "year">
        <span>CVV: </span>
    </div>
    <div id = "cvv_div">
        <input type = "text" name = "cvv" id = "cvv">
    </div>
    </div> -->
    <div id = "checkout_div">
    <span>Sub Total: </span>
    <br><br><br>
    <span>Membership discount of 20%: </span>
    <br><br><br>
    <span><b>Total Amount: </b></span>
    <span><b><%= number_to_currency(@total, :unit => '€') %></b></span>
    </div>
     <br><br><br><br>
<%= link_to "Confirm Payment".html_safe, page_confirmation_path, :class => "btn btn-primary" %>
    

app/views/page/confirmation.html.erb
<h1>Order Confirmation</h1>
<p>Thank you for your purchase. Enjoy your treatment</p>

app/views/page/order.html.erb
<h1>Page#order</h1>
<p>Find me in app/views/page/order.html.erb</p>