config/routes.rb
Rails.application.routes.draw do
  get 'page/checkout' 
  get 'page/confirmation'
  get 'page/order'

  resources :carts
  resources :line_items
  resources :products
  resources :charges
  devise_for :users

  root 'home#index'
  
 get 'account' => 'account#index'
 get "/account/:page" => "account#show"

end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :line_items
    belongs_to :category
    
    def self.search(search)
        where("name LIKE ?", "%#{search}%") 
        where("description LIKE ?", "%#{search}%")
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    #if the param passed are category
    if params[:category]
      #gets id of params that is being passed in url
      @category_id = Category.find_by(name: params[:category]).id
      #get products that match this category
      @products = Product.where(:category_id => @category_id)
    elsif params[:search]
      @products = Product.search(params[:search])
    else
      @products = Product.all
    end
  end
  
  # GET /products/1
  # GET /products/1.json
  def show
     
  end

  # GET /products/new
  def new
    @product = Product.new
    #create array of category name and id for drop down in the view
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    #associate a product with a category id selected
    @product.category_id = params[:category_id]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
     #associate a product with a category id selected
    @product.category_id = params[:category_id]
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # Add category id to this to allow it to save
    def product_params
      params.require(:product).permit(:name, :length, :description, :price, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
 <div class="form-group">
   <%= f.label :category %>
   <% if current_page?("/products/new") %>
      <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category" , class:"form-control")  %>
   <% else %>
      <%= f.select :category_id,  @categories  %>
   <% end %>
   </div>
   <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :length %>
    <%= f.text_field :length, class:"form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Add new product", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Show', @product, class: "btn btn-default" %> 
   <%= link_to 'Back', products_path, class: "btn btn-default" %>
</p>

app/views/products/index.html.erb
<div class="row">
  <div class="col-md-2 sidebar">
    <ul class="nav nav-sidebar">
      <li class="<%= 'active' if params[:category].blank? %>"><%= link_to "All", products_path %></li>
      <!-- for each category -->
      <% Category.all.each do | category | %>
           <!-- get name of each instance and pass name of category in the url as a parameter -->
           <li class="<%= 'active' if params[:category] == category.name %>"><%= link_to category.name, products_path(category: category.name) %></li>
      <% end %>
    </ul>
    </div>
    <div class="col-md-10">
      <p id="notice"><%= notice %></p>
      <!-- search text field -->
      <%= form_tag(products_path, :method => "get", class: "form-inline search") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search treatments", class:"search-query form-control" %>
          <%= submit_tag "Search", class:"btn btn-primary"%>
      <% end %>
      <!-- if user has admin rights show add new product -->
       <% if current_user.try(:admin?) %>
         <%= link_to 'Add New Product', new_product_path, class: "btn btn-default" %>
      <% end %>
      <h1>Treatments</h1>
      <!-- shows the current category -->
      <h2><%= params[:category] %></h2>
      <!-- if no products match show message -->
        <% if @products.count == 0 %>
          <p>There are no treatments currently available for this category.</p>
          <!-- else show products -->
        <% else %>
          <% @products.each do |product| %>
            <h3><%= product.name %></h3>
            <h4><%= product.length %></h4>
            <p><%= product.description %></p>
            <p><strong><%= number_to_currency(product.price, :unit => '€') %></strong></p>
            <%= button_to "Add to cart", line_items_path(:product_id => product), :class => 'btn btn-primary' %>
            <!-- if current user is admin https://github.com/plataformatec/devise/wiki/How-To:-Add-an-Admin-Role -->
            <% if current_user.try(:admin?) %>
              <p>
                <%= link_to 'Show', product, class: "btn btn-default" %> 
                <%= link_to 'Edit', edit_product_path(product), class: "btn btn-default" %> 
                <%= link_to 'Destroy', product, class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
              </p>
            <% end %>
            <hr/>
          <% end %>
        <% end %>
    </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path, class: "btn btn-default" %>

app/views/products/show.html.erb
<h3><%= @product.name %></h3>
<h4><%= @product.length %></h4>
<p><%= @product.description %></p>
<p><strong>&euro;<%= @product.price %></strong></p>
<p>
    <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-default" %>
    <%= link_to 'Back', products_path, class: "btn btn-default" %>
</p>