config/routes.rb
Rails.application.routes.draw do
  get 'page/checkout' 
  get 'page/confirmation'
  get 'page/order'

  resources :carts
  resources :line_items
  resources :products
  resources :charges
  devise_for :users

  root 'home#index'
  
 get 'account' => 'account#index'
 get "/account/:page" => "account#show"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Health Spa Dublin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <!-- NAV -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/"><%= image_tag("logo.png", :alt => "Health Spa") %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Treatments", products_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Membership", "/account/membership" %></li>
              <% if user_signed_in? %>
              <li><%= link_to "My Account", account_path %></li>
               <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
               <li>
                 <a href="/carts/show" class="cart">
                   <span class="glyphicon glyphicon-shopping-cart"></span> 
                  <%= number_to_currency(@cart.total_price, :unit => '€') %><br/>
                  <span class="my-bag">My bag(<%= @cart.total_items %>)</span>
                </a>
              </li>
            <% else %>
                <li><%= link_to "Register", new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="row">
      <%= yield %>
     </div>
        </div>

</body>
</html>